# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

# Tesing all stored valid user inputs with browser engine
# This may take some DAYS to process 

name: Full Frontend Test

on: workflow_dispatch # triggers test manually

jobs:
  full-frontend-test:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        cache: 'npm'
    - name: Install Webdriver manager
      run: sudo npm i -g webdriver-manager
    - name: Install browser engines
      run: | 
        sudo webdriver-manager update --out_dir /usr/local/bin
        ls -alF /usr/local/bin
        sudo rm /usr/local/bin/*.zip /usr/local/bin/*.tar.gz
        sudo mv /usr/local/bin/chromedriver* /usr/local/bin/chromedriver
        sudo mv /usr/local/bin/geckodriver* /usr/local/bin/geckodriver
        ls -alF /usr/local/bin/geckodriver /usr/local/bin/chromedriver
    - name: Install package
      run: npm ci
    - name: Test Frontend with all valid user inputs
      run: npm run test:fullFrontend
