# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Mac OS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  macos:
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    runs-on: macos-latest
    env:
      NODE_ENV: test

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install imagemagick
      run: brew install imagemagick
    - run: npm ci
    - run: npm run test:macos
