# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ubuntu:
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install imagemagick
      run: sudo apt-get install imagemagick
    - run: npm ci
    - run: npm test
    
  macos:
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        
    runs-on: macos-latest
    env:
      NODE_ENV: test

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install imagemagick
      run: brew install imagemagick
    - run: npm ci
    - run: npm test

  windows:
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        
    runs-on: windows-latest
    env:
      NODE_ENV: test

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install imagemagick
      run: '@"%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command "[System.Net.ServicePointManager]::SecurityProtocol = 3072; iex ((New-Object System.Net.WebClient).DownloadString(''https://chocolatey.org/install.ps1''))" && SET "PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin"'
    - run: npm ci
    - run: npm test
