# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  windows:
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    runs-on: windows-latest
    env:
      NODE_ENV: test

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install imagemagick
      run: choco install imagemagick
    - name: Rename imagemagick executable
      run: | 
        cd "C:\Program Files\ImageMagick-7.1.0-Q16-HDRI\"
        dir
        copy magick.exe convert.exe
        where magick.exe
        where convert.exe
        setx PATH "C:\Program Files\ImageMagick-7.1.0-Q16-HDRI\;%PATH%"
        where magick.exe
        where convert.exe
    - run: npm ci
    - run: npm test
